build:
  environment:
    php:
      version: 5.6

filter:
    excluded_paths: [test/*]

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage: true