language: php
php:
  - "5.6"
  - hhvm
  - "7.0"

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer validate
  - composer update

script: 
    - phpunit src/CLogControllerTest.php --coverage-clover coverage.clover
    - phpunit src/TableLogTest.php --coverage-clover coverage.clover

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover